### ISSUE TITLE
env TERM issue

### ISSUE THREAD

**Issue by ksexton** [aergonaut/aether#1]
I was running into the same tput issue and was able to resolve it by adding

```
  environment.variables = {
    TERMINFO_DIRS = "${pkgs.kitty.terminfo.outPath}/share/terminfo";
  };
```

to my nix-darwin config.  It looks like you are trying to set it in the zsh portion of your home-manager config, try moving it out of home-manager and into your darwin config to see if that helps.

**Comment by aergonaut** [comment]
Thanks @ksexton. This totally helped and now it's working perfectly!
